### ISSUE TITLE
Golang library

### ISSUE THREAD

**Issue by ligurio** [reportportal/service-api#1094]
I don't use Report Portal at all but I want to integrate my application written on Go with Report Portal. Is there Go package for it or may be swagger doc?

**Comment by evjlobanova** [comment]
@ligurio Hello, we do not have an integrations with Go frameworks. If you want you can contribute to ReportPortal. We have prepared a dev guide with full deescription on how to report results to RP https://github.com/ihar-kahadouski/dev-guide/blob/master/reporting.md

If you have questions, @ihar-kahadouski can help you and consult.
Al  dev guides you can find [here](https://reportportal.io/docs/Developers-guide)

**Comment by inluxc** [comment]
Hi there, you can use https://github.com/avarabyeu/goRP, Right now I implementing with GoDog and Tebeka.

Monday or Tuesday I will have a GIST with and example.

**Comment by inluxc** [comment]
Right now, it's still at a very early stage.
https://github.com/DATA-DOG/godog/pull/206/files

But I will continue with it in a week or so, need to deploy RP in AWS ECS first.
