### ISSUE TITLE
Cannot update launch with tag without key value pair

### ISSUE THREAD

**Issue by arybkin** [reportportal/service-api#1190]
Hello guys,

I have faced next case:

We can't update launch with email name (or another value) in attribute, if email is set as tag (without key/value pair). But we can set email in tags if we set it on launch creation.

Create launch with api /v1/{projectName}/launch. Use next body:
{
  "attributes": [
    {
      "key": "email",
      "value": "email@value.com"
    },
  "email@simple@asd.com"
  ],
  "description": "string",
  "mode": "DEFAULT",
  "name": "Test_attribute",
  "rerunOf": "string",
  "startTime": "2020-04-15T07:39:20.951Z"
}

Launch is created successfully with all defined tags:
![image](https://user-images.githubusercontent.com/6349907/79312042-ff6baf00-7f06-11ea-8214-ddf0455e678d.png)

Then try to update this launch with api /v1/{projectName}/launch/{launchId}/update
Body:
{
  "attributes": [
    {
      "key": "another_email",
      "value": "second@email.com"
    },
   "second_free@email.com"
  ],
  "description": "string",
  "mode": "DEFAULT"
}

Response 400:
{
  "errorCode": 4001,
  "message": "Incorrect Request. JSON parse error: Cannot construct instance of `com.epam.ta.reportportal.ws.model.attribute.ItemAttributeResource` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('second_free@email.com'); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.epam.ta.reportportal.ws.model.attribute.ItemAttributeResource` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('second_free@email.com')\n at [Source: (PushbackInputStream); line: 7, column: 1] (through reference chain: com.epam.ta.reportportal.ws.model.launch.UpdateLaunchRQ[\"attributes\"]->java.util.HashSet[1])"
}

**Comment by Yumfriez** [comment]
@evjlobanova Should be reproduced on our side. We need a JIRA-ticket

**Comment by evjlobanova** [comment]
@e-olga @svettsova could you please try to reproduce issue?

**Comment by e-olga** [comment]
@evjlobanova The issue is reproduced and the ticket is added to JIRA
The update of launch with the attribute value as a string will be possible, the same as on start of launch
