### ISSUE TITLE
Clean job filters projects incorrectly

### ISSUE THREAD

**Issue by serhiikachan** [reportportal/service-api#1271]
Since we have a big amount of projects in RP in database are stored more than 100 project ids. Project that we need to clean up has id 117.
Used a debug logger mode to get more details and cleaning wasn't even started for project with id = 117.
It seems like query that collects projects for cleaning doesn't work properly.

Here is the part of log we expected to see but we didn't: 
`INFO 6 --- [gs-job-thread-1] c.epam.ta.reportportal.job.CleanLogsJob  : Cleaning outdated logs for project 117 has been finished. Total logs removed: {some amount}`

Please see the log attached.
[rp_api_debug.zip](https://github.com/reportportal/service-api/files/5035446/rp_api_debug.zip)

**Comment by miracle8484** [comment]
Hello, please use latest version of RP (for now 5.7.2), cleaning jobs has been completely refactored.
