### ISSUE TITLE
Will v5.4.0 be indexed in Maven Central?

### ISSUE THREAD

**Issue by matthewbednarski** [reportportal/service-api#1405]
Will Reportportal service-api v5.4.0 ever find it's way to Maven-Central? 
Currently it's at v5.3.5.

**Comment by HardNorth** [comment]
@Yumfriez, @miracle8484, @pbortnik , the question for you guys.

**Comment by miracle8484** [comment]
Hello, @matthewbednarski, we recommend to use the recent version of service-api  available here https://mvnrepository.com/artifact/com.epam.reportportal/service-api/5.7.2
