### ISSUE TITLE
service api without rabbitmq

### ISSUE THREAD

**Issue by paramadeep** [reportportal/service-api#1464]
I understand we user rabbitmq for the purpose of analysis. Please correct me if my understanding is wrong.

We intend to use rp for aggregation of the test execution to start with with manual tagging of the issues. 

is there a config that we could use disable any need for analyzer and deploy without rabbitmq.

**Comment by HardNorth** [comment]
@paramadeep Short answer is no. We use rabbit not only for analyzer.
