### ISSUE TITLE
Not able to find Report Portal Service API executable JAR 

### ISSUE THREAD

**Issue by satishkumar9549** [reportportal/service-api#1606]
We are upgrading Linux version of Report Portal to 5.7.2 and tried downloading the API file from below URL:
curl -L $MAVEN_REPO/service-api/$API_VERSION/service-api-$API_VERSION-exec.jar -o service-api.jar but there is no executable jar file available in the url: https://repo1.maven.org/maven2/com/epam/reportportal/service-api/5.7.2/

Can you please provide this file so that we can upgrade report portal to latest version.

**Comment by DzmitryHumianiuk** [comment]
closed as duplicate to https://github.com/reportportal/reportportal/issues/1791
