### ISSUE TITLE
Unable to login with SAML into RP after upgrading from 5.3.5 to 5.7.4

### ISSUE THREAD

**Issue by Swati-singh1** [reportportal/service-api#1699]
We are unable to access ReportPortal through our SAML integration and getting 400 Bad request, BAD SAML error.
Please look into the logs and help us resolve the error.
[RP Logs.docx](https://github.com/reportportal/service-api/files/11306675/RP.Logs.docx)
Logs:
```
ERROR 1 --- [io-8585-exec-34] .AuthUtils$SerialUidReplacingInputStream : Potentially Fatal Deserialization Operation.
java.io.InvalidClassException: Overriding serialized class version mismatch: local serialVersionUID = 550 stream serialVersionUID = 520
ERROR 1 --- [nio-9999-exec-7] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Auth integration 'Oauth settings with id = github have not been found.' not found. Did you use correct name?
com.epam.ta.reportportal.exception.ReportPortalException: Auth integration 'Oauth settings with id = github have not been found.' not found. Did you use correct name?
```
[RP service-aut logs.docx](https://github.com/reportportal/service-api/files/11306704/RP.service-aut.logs.docx)

**Comment by DzmitryHumianiuk** [comment]
@Swati-singh1 do you have a superadmin or any other admin user still available (the one which is not synced with SAML)?

if so, please login, delete the integration. install and configure it again.

**Comment by Swati-singh1** [comment]
@DzmitryHumianiuk Yes we did try that already. Do you want me to remove the configuration from Okta as well and reconfigure in reportportal?

**Comment by DzmitryHumianiuk** [comment]
@Swati-singh1 This is the best recommendation I can provide based on the information available to me.

**Comment by alena-babrova** [comment]
Full recreation of integration (delete -> create) has helped.
