### ISSUE TITLE
service-api gets unhealthy state after postgresSQL deadlock

### ISSUE THREAD

**Issue by qasamppa** [reportportal/service-api#1720]
I am not sure, if this is correct place for this issue... Suddenly service-api noticed postgreSQL deadlock while updating test-results. What might cause this?
We have docker solution in use and latest docker-compose.yml without modifications
Only change we made was this elastic search data folder group and rights change based on ReportPortal documentation. This was mandatory.
[Known issue 1](https://reportportal.io/docs/issues-troubleshooting/ResolveAnalyzerKnownIssues#problem-1-auto-analyser-doesnt-work-analyzer-health-check-status-failed-elasticsearch-is-not-healthy)

`Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 7473 waits for ShareLock on transaction 6373; blocked by process 7359.
Process 7359 waits for ShareLock on transaction 7083; blocked by process 7473.
  Hint: See server log for query details.
  Where: while updating tuple (3,192) in relation "test_item_results"`
[reportportal.zip](https://github.com/reportportal/service-api/files/11902252/reportportal.zip)

**Comment by VeranikaRymzha** [comment]
Hello @qasamppa,
I wanted to let you know that the ReportPortal 24.2 version is now live, along with the improvement you've requested. So I will close this GitHub issue.

You can find more details about the new features and enhancements in the [release notes](https://reportportal.io/docs/releases/Version24.2/). 
Feel free to try it out and share any feedback you may have.

Have a great day!
