### ISSUE TITLE
How to increase logSize entry in reportportal

### ISSUE THREAD

**Issue by willyhalim** [reportportal/service-api#1912]
Hi,

Recently we realized that log entries in our test items for each launch is only 2560 entry.

Is there anyway we can increase this ?

We are deploying reportportal using docker using version 5.6.0

**Comment by willyhalim** [comment]
Seems this issue is resolved if i add this in the client ( reportportal.properties )
`rp.batch.size.logs = 200`

**Comment by Pink-Bumblebee** [comment]
Resolved by issuer
