### ISSUE TITLE
Getting org.hibernate.exception.GenericJDBCException while running playwright tests

### ISSUE THREAD

**Issue by anud22** [reportportal/service-api#1937]
Getting error - Failed to send log Error: Request failed with status code 500: {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.GenericJDBCException: could not execute statement]" How i can troubleshoot this issue? Thanks

**Comment by AmsterGet** [comment]
@anud22 Could you please share your ReportPortal version?

**Comment by AmsterGet** [comment]
@alena-babrova can anyone from the QA team help here?

**Comment by alena-babrova** [comment]
Hello @anud22,

Could you please provide:
1. version of ReportPortal
2. what action do you execute when getting the error

Thanks!
