### ISSUE TITLE
[BUG] LaunchImpl.finish(FinishExecutionRQ) doesn't update 'launch.description' field

### ISSUE THREAD

**Issue by shaburov** [reportportal/service-api#1951]
'com.epam.reportportal.service.LaunchImpl.finish(FinishExecutionRQ)'

FinishExecutionRQ contains filled description field
The request is carried out without errors
Description is not filled in the launch

![image](https://github.com/reportportal/service-api/assets/15269131/9f00ec22-748c-4680-a842-5600dbbb5860)

![image](https://github.com/reportportal/service-api/assets/15269131/526c90fc-5c23-405a-8da0-67495fd65805)

![image](https://github.com/reportportal/service-api/assets/15269131/eef7c659-40e1-4101-b91d-4cf9c8e6728e)

**Comment by Pink-Bumblebee** [comment]
Hello @shaburov . Thank you for your highlight. We've checked this issue, and - yes, you've found bug. We will fix it in one of our future releases.
For now, QA proposed you to use workaround. When you start new launch, please add to your report one more string : `"description" : "" `. 
![image](https://github.com/reportportal/service-api/assets/145099680/edb7c17b-8a0e-4ad4-9458-6063d4ed3de6)

In this case, when you execute finish of launch with some information in description field, this information will become visible.

**Comment by Kozovskaya** [comment]
Hello @shaburov 
we've made the fix, it will be available in 24.2 release version.
Thanks for highlighting the issue!

**Comment by Kozovskaya** [comment]
Hello @shaburov 
The ReportPortal version 24.2 is already released!
I'm closing the issue.
Thank you for using ReportPortal!
