### ISSUE TITLE
Finish test item v1 and v2 endpoints behaves differently when there is a test item with skipped status and with some steps passed and skipped.

### ISSUE THREAD

**Issue by d2575094** [reportportal/service-api#2084]
For example, a test contains five steps. The first three passes and the next two are skipped. The test item is marked as skipped. 
When I report the test result using the v1 endpoints, the test is marked as "Skipped" in ReportPortal as expected.
When I report the test result using v2 endpoints, the test result is marked as "Failed" in ReportPortal.
 Why do we see the discrepancy between these versions?
 
 When I use the v2 finish test item (put) alone to update the status from "failed" to "skipped," it gets updated successfully.
Please let me know if I need to include any configurations using the v2 endpoints. 
We are on report portal 24.1 version.

**Comment by HardNorth** [comment]
Duplicates: https://github.com/reportportal/reportportal/issues/2387
