### ISSUE TITLE
CORS seems to be unsupported

### ISSUE THREAD

**Issue by freesbe** [reportportal/service-api#296]
Cross origin requests fails when browser sends pre-flight OPTIONS request.

Pre-flight request:
```
OPTIONS
https://rp.epam.com/api/v1/viachaslau_balashevich_personal/launch/latest?page.page=1&page.size=50&page.sort=start_time%2CDESC
```

Pre-flight request headers:
```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET
Connection: keep-alive
Host: rp.epam.com
Origin: http://localhost:3000
Referer: http://localhost:3000/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
```
There is no _Authorization_ header obviously - it's added to GET request, not to the pre-flight one.

Request which causes browser to fire pre-flight:
```
GET
https://rp.epam.com/api/v1/viachaslau_balashevich_personal/launch/latest?page.page=1&page.size=50&page.sort=start_time%2CDESC
```

with header:
```
Authorization': 'bearer there_is_some_valid_token'
```

Error:
> Failed to load https://rp.epam.com/api/v1/viachaslau_balashevich_personal/launch/latest?page.page=1&page.size=50&page.sort=start_time%2CDESC: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by avarabyeu** [comment]
hi @freesbe 
Unfortunately, i cannot reproduce the issue:
```sh
curl -i -X OPTIONS -H "Authorization: Bearer MY_TOKEN" "https://rp.epam.com/api/v1/viachaslau_balashevich_personal/launch/latest?page.page=1&page.size=50&page.sort=start_time%2CDESC"
HTTP/2 200
date: Fri, 06 Apr 2018 10:25:07 GMT
content-length: 0
allow: GET,HEAD,DELETE
cache-control: no-cache, no-store, max-age=0, must-revalidate
expires: 0
pragma: no-cache
x-application-context: api:docker:8080
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-frame-options: SAMEORIGIN
access-control-allow-origin: http://rp.epam.com
cache-control: public, must-revalidate
```

Could you please make sure your token is not expired?

**Comment by freesbe** [comment]
In your example there is an _Authorization_ header in OPTIONS request, but as I mentioned it should not be added:

> There is no Authorization header obviously - it's added to GET request, not to the pre-flight one.

I found, CORS headers are missing in current implementation. For OPTIONS response I would expect:

```
"Access-Control-Allow-Origin": "hostname",
"Access-Control-Allow-Headers": "Authorization, ...",
"Access-Control-Allow-Method": "GET, POST, ..."
```

Also, `Access-Control-Allow-Origin` header is missing for other types of responses - `GET` etc.

**Comment by freesbe** [comment]
@avarabyeu any update on this?
