### ISSUE TITLE
{ProjectName} in URI is case sensitive for getting items

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/service-api#451]
Steps:
1. Create launch
2. Create test
3. Get tests in the launch

Result:
```GET https://rp.epam.com/api/v1/Ci-agents-checks/item/?&filter.eq.launch=5bfe491c3cdea20001229aba&filter.eq.name=dc1cbc80-f5ab-4e56-8a76-5aae1719bf17
Response Body: {"error_code":40010,"message":"Forbidden operation. Specified launch with id '5bfe491c3cdea20001229aba' not referenced to specified project 'Ci-agents-checks'"}
```

You can see that client used `Ci-agents-checks` project name for all requests. Please see curl commands to reproduce the issue: [Issue.txt](https://github.com/reportportal/service-api/files/2623446/Issue.txt)

Workaround:
The issue is not reproducible if client uses `ci-agents-checks` project name (lower case `c`).

**Comment by pbortnik** [comment]
will be fixed in 5.0 version

**Comment by evjlobanova** [comment]
@pbortnik could you please check if it has been fixed?

**Comment by e-olga** [comment]
Works correctly (the project name is case insensitive) in version RP v.5.0

Regards,
Olga
