### ISSUE TITLE
Github is set to display develop as primary branch

### ISSUE THREAD

**Issue by gkalnytskyi** [reportportal/service-api#676]
This Github repository is set to display `develop` as primary branch when it was last updated 5 months ago. while master was updated a week ago. This may lead some people to think that the project is abandoned.

Is this setup correct?

**Comment by DzmitryHumianiuk** [comment]
@gkalnytskyi it right.
and it is actual.

we follow git-flow.

`master` is locked branch for stable release version. Currently 4.3.6
`develop` is development branch for version 4.3.6+. Keeps all updates for version 4.x and merges into **master** on release day.
`ps-migration` stands for PostgreSQL-migration. is an active branch for 5.0 version.

**Comment by gkalnytskyi** [comment]
Ok, got it. Thank you for clarifying this. The commit timeline misled me a little.
