### ISSUE TITLE
Get list of all projects

### ISSUE THREAD

**Issue by ekisielinski** [reportportal/service-api#730]
Hi,

is it possible to get list of all projects through rest API (and also .NET client)?

I cannot see it. I want to gather all launches from all projects to create some overall statistics in my application. Currently I need to hardcode project names in my code.

I would be nice to get all projects through rest for specified user.

**Comment by nvborisenko** [comment]
Seems `GET api/v1/user` returns information about projects which current user is assigned to. Hmm, not documented.
To support it on .net client side we need extend client, simple work item.

**Comment by nvborisenko** [comment]
Available in `ReportPortal.Client 2.1.12`
via
```csharp
var user = await service.GetUserAsync();
var projects = user.AssignedProjects;
```

**Comment by nvborisenko** [comment]
Closing it. Feel free to reopen if it doesn't work.
